// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ItemWithPosition item with position
//
// swagger:model ItemWithPosition
type ItemWithPosition struct {
	Item

	// position
	Position int64 `json:"position,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ItemWithPosition) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Item
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Item = aO0

	// AO1
	var dataAO1 struct {
		Position int64 `json:"position,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Position = dataAO1.Position

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ItemWithPosition) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Item)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Position int64 `json:"position,omitempty"`
	}

	dataAO1.Position = m.Position

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this item with position
func (m *ItemWithPosition) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Item
	if err := m.Item.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this item with position based on the context it is used
func (m *ItemWithPosition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Item
	if err := m.Item.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ItemWithPosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ItemWithPosition) UnmarshalBinary(b []byte) error {
	var res ItemWithPosition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
