// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID         uuid.UUID
	Title      string
	DateCreate time.Time
}

type ItemList struct {
	ListID   uuid.UUID
	ItemID   uuid.UUID
	Position sql.NullInt32
}

type List struct {
	ID         uuid.UUID
	OwnerID    int32
	Title      string
	DateCreate sql.NullTime
}

type Session struct {
	ID          uuid.UUID
	UserID      int32
	DateCreate  time.Time
	DateExpires sql.NullTime
}

type User struct {
	ID           int32
	Email        string
	PasswordHash []byte
}
