// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
)

type Item struct {
	ID         uuid.UUID
	Title      string
	DateCreate sql.NullTime
}

type ItemList struct {
	ListID   uuid.UUID
	ItemID   uuid.UUID
	Position sql.NullInt32
}

type List struct {
	ID         uuid.UUID
	Title      string
	DateCreate sql.NullTime
}
